# Air configuration file (.air.toml)
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
# Binary file yields from `cmd`.
bin = "./tmp/main.exe"
# Watch these directories for changes
include_dir = ["cmd", "internal", "pkg"]
# Exclude directories and files from watching
exclude_dir = ["tmp", "vendor", ".git", "bin"]
# Exclude files from watching
exclude_file = []
# This log file places in your tmp_dir.
log = "air.log"
# Poll files for changes instead of using fsnotify.
poll = false
# Poll interval (defaults to 500ms)
poll_interval = 500 # ms
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
