version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: makwatches-be:local
    container_name: makwatches-be
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      # Point API to the MongoDB container
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=pehnaw
      # Point API to the Redis container (optional, app continues without Redis if down)
      - REDIS_URI=redis:6379
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: makwatches-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: makwatches-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongodb_data: