version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pehnaw-api
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pehnaw
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: pehnaw-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pehnaw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Uncomment if you want to use MongoDB instead
  # mongodb:
  #   image: mongo:6.0
  #   container_name: pehnaw-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=example
  #     - MONGO_INITDB_DATABASE=pehnaw
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped

volumes:
  postgres_data:
  # mongodb_data:  # Uncomment if using MongoDB